[c-import] initialize Clang builtins
To avoid errors like this:

> /usr/local/lib/clang/3.9.0/include/mmintrin.h:64:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
>     return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
>            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

A big thanks to this commit (https://github.com/Meinersbur/pet/commit/1af9b3eb920b8c2608baddf74931b8559c08e55b)
for the way to do this properly.

Also, the line "ci.getPreprocessorOpts().UsePredefines = false;" did
nothing because it was called _after_ createPreprocessor() so this
commit also removes that.