Fix "DSO missing from command line" on Ubuntu 20
Full error:

/usr/bin/ld: /tmp/cx-4378e7.o: undefined reference to symbol 'sqrtf@@GLIBC_2.17'
/usr/bin/ld: /lib/aarch64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line